let ingredients = [
    "Lait de coco",
    "Jus de citron",
    "Crème de coco",
    "Sucre",
    "Glaçons",
    "Thon Rouge (ou blanc)",
    "Concombre",
    "Tomate",
    "Carotte",
    "Citron Vert",
    "Lait de Coco",
    "Poulet",
    "Lait de coco",
    "Coulis de tomate",
    "Oignon",
    "Poivron rouge",
    "Huile d'olive",
    "Riz blanc",
    "Thon en miettes",
    "Tomate",
    "Oeuf dur",
    "Maïs",
    "Vinaigrette",
    "Pâte feuilletée",
    "Thon en miettes",
    "Tomate",
    "Crème fraiche",
    "gruyère râpé",
    "Moutarde de Dijon",
    "Pâte brisée",
    "Pomme",
    "Oeuf",
    "Crème fraiche",
    "Sucre en Poudre",
    "Sucre vanillé",
    "Pâte sablée",
    "Chocolat au lait",
    "Crème liquide",
    "Beurre",
    "Fraise",
    "Noix",
    "Chocolat noir",
    "Beurre",
    "Oeuf",
    "Sucre en Poudre",
    "farine",
    "Concombre",
    "Olives",
    "Fromage de chèvre",
    "Vinaigre Balsamic",
    "Huile d'olive",
    "Basilic",
];